import { buildReportStyles } from '../../shared/pdf/pdf.service'

const now = () => new Date().toLocaleString()

function esc(s: any): string {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function statusBadge(status: string): string {
  const cls = status === 'valid' || status === 'completed' || status === 'approved' || status === 'active' || status === 'resolved' || status === 'paid'
    ? 'status-valid'
    : status === 'pending' || status === 'expiring' || status === 'under review'
    ? 'status-warning'
    : status === 'critical' || status === 'high' || status === 'expired' || status === 'deactivated' || status === 'rejected'
    ? 'status-critical'
    : 'status-neutral'
  return `<span class="${cls}">${esc(status)}</span>`
}

function coverPage(title: string, orgName: string, description: string): string {
  return `<div class="cover">
    <div class="badge">${esc(orgName)}</div>
    <h1>${esc(title)}</h1>
    <p class="subtitle">${esc(description)}</p>
    <div class="meta">Generated by CareDesk &bull; ${now()}</div>
  </div>`
}

function table(headers: string[], rows: string[][]): string {
  return `<table>
    <thead><tr>${headers.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead>
    <tbody>${rows.map(r => `<tr>${r.map((c: string) => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody>
  </table>`
}

function toCsv(headers: string[], rows: string[][]): string {
  return '\uFEFF' + [headers, ...rows].map(r => r.map((c: string) => `"${c.replace(/"/g, '""')}"`).join(',')).join('\n')
}

// --- Staff Compliance Summary ---
export function buildStaffComplianceHtml(data: any, orgName = 'CareDesk'): string {
  const rows = (data.staff || []).map((s: any) => [
    `${esc(s.first_name)} ${esc(s.last_name)}`,
    esc(s.role || s.compliance_profile || '-'),
    `${s.compliance_rate ?? 0}%`,
    statusBadge(s.dbs_status || 'unknown'),
    statusBadge(s.training_status || 'unknown'),
    s.last_review ? new Date(s.last_review).toLocaleDateString() : '-',
  ])
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${buildReportStyles()}</style></head><body>
    ${coverPage('Staff Compliance Summary', orgName, 'Overview of staff compliance status across all requirements')}
    <h1>Executive Summary</h1>
    <div class="summary-grid">
      <div class="summary-card"><div class="num">${data.staff?.length || 0}</div><div class="label">Total Staff</div></div>
      <div class="summary-card"><div class="num">${data.compliant_count ?? 0}</div><div class="label">Fully Compliant</div></div>
      <div class="summary-card"><div class="num">${data.at_risk_count ?? 0}</div><div class="label">At Risk</div></div>
    </div>
    <h2>Staff Compliance Details (${rows.length})</h2>
    ${rows.length ? table(['Staff Name', 'Role', 'Overall %', 'DBS Status', 'Training Status', 'Last Review'], rows) : '<p>No staff data.</p>'}
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #D1D5DB;font-size:10px;color:#9CA3AF;text-align:center">CareDesk Report &bull; Generated ${now()}</div>
  </body></html>`
}

export function staffComplianceCsv(data: any): string {
  const headers = ['Staff Name', 'Role', 'Compliance %', 'DBS Status', 'Training Status', 'Last Review']
  const rows = (data.staff || []).map((s: any) => [
    `${s.first_name} ${s.last_name}`,
    s.role || s.compliance_profile || '',
    String(s.compliance_rate ?? 0),
    s.dbs_status || '',
    s.training_status || '',
    s.last_review ? new Date(s.last_review).toLocaleDateString() : '',
  ])
  return toCsv(headers, rows)
}

// --- Training Matrix Export ---
export function buildTrainingMatrixHtml(data: any, orgName = 'CareDesk'): string {
  const rows = (data.records || []).map((r: any) => [
    `${esc(r.first_name)} ${esc(r.last_name)}`,
    esc(r.module_name),
    esc(r.module_category || '-'),
    statusBadge(r.status || 'pending'),
    r.completed_at ? new Date(r.completed_at).toLocaleDateString() : '-',
    r.expires_at ? new Date(r.expires_at).toLocaleDateString() : '-',
  ])
  const completed = (data.records || []).filter((r: any) => r.status === 'completed').length
  const expired = (data.records || []).filter((r: any) => r.status === 'expired').length
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${buildReportStyles()}</style></head><body>
    ${coverPage('Training Matrix Export', orgName, 'Staff training module completion matrix')}
    <h1>Training Summary</h1>
    <div class="summary-grid">
      <div class="summary-card"><div class="num">${data.records?.length || 0}</div><div class="label">Total Records</div></div>
      <div class="summary-card"><div class="num">${completed}</div><div class="label">Completed</div></div>
      <div class="summary-card"><div class="num">${expired}</div><div class="label">Expired</div></div>
    </div>
    <h2>Training Records (${rows.length})</h2>
    ${rows.length ? table(['Staff Name', 'Module', 'Category', 'Status', 'Completed', 'Expires'], rows) : '<p>No training records.</p>'}
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #D1D5DB;font-size:10px;color:#9CA3AF;text-align:center">CareDesk Report &bull; Generated ${now()}</div>
  </body></html>`
}

export function trainingMatrixCsv(data: any): string {
  const headers = ['Staff Name', 'Module', 'Category', 'Status', 'Completed', 'Expires']
  const rows = (data.records || []).map((r: any) => [
    `${r.first_name} ${r.last_name}`,
    r.module_name,
    r.module_category || '',
    r.status || '',
    r.completed_at ? new Date(r.completed_at).toLocaleDateString() : '',
    r.expires_at ? new Date(r.expires_at).toLocaleDateString() : '',
  ])
  return toCsv(headers, rows)
}

// --- Incident Log ---
export function buildIncidentLogHtml(data: any, orgName = 'CareDesk'): string {
  const rows = (data.incidents || []).map((inc: any) => [
    new Date(inc.occurred_at || inc.created_at).toLocaleDateString(),
    esc(inc.location_name || '-'),
    esc(inc.category || inc.incident_type || '-'),
    statusBadge(inc.severity || 'low'),
    `${esc(inc.reported_by_first || '')} ${esc(inc.reported_by_last || '')}`,
    statusBadge(inc.status || 'Open'),
    esc(inc.resolution || '-'),
  ])
  const critical = (data.incidents || []).filter((i: any) => i.severity === 'critical' || i.severity === 'high').length
  const open = (data.incidents || []).filter((i: any) => i.status !== 'closed' && i.status !== 'resolved').length
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${buildReportStyles()}</style></head><body>
    ${coverPage('Incident Log', orgName, 'Categorized incident reports by type and severity')}
    <h1>Incident Summary</h1>
    <div class="summary-grid">
      <div class="summary-card"><div class="num">${data.incidents?.length || 0}</div><div class="label">Total Incidents</div></div>
      <div class="summary-card"><div class="num">${critical}</div><div class="label">Critical / High</div></div>
      <div class="summary-card"><div class="num">${open}</div><div class="label">Open</div></div>
    </div>
    <h2>Incident Details (${rows.length})</h2>
    ${rows.length ? table(['Date', 'Location', 'Type', 'Severity', 'Reported By', 'Status', 'Resolution'], rows) : '<p>No incidents recorded.</p>'}
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #D1D5DB;font-size:10px;color:#9CA3AF;text-align:center">CareDesk Report &bull; Generated ${now()}</div>
  </body></html>`
}

export function incidentLogCsv(data: any): string {
  const headers = ['Date', 'Location', 'Type', 'Severity', 'Reported By', 'Status', 'Resolution']
  const rows = (data.incidents || []).map((inc: any) => [
    new Date(inc.occurred_at || inc.created_at).toLocaleDateString(),
    inc.location_name || '',
    inc.category || inc.incident_type || '',
    inc.severity || '',
    `${inc.reported_by_first || ''} ${inc.reported_by_last || ''}`.trim(),
    inc.status || '',
    inc.resolution || '',
  ])
  return toCsv(headers, rows)
}

// --- Leave Overview ---
export function buildLeaveOverviewHtml(data: any, orgName = 'CareDesk'): string {
  const rows = (data.balances || []).map((b: any) => [
    `${esc(b.first_name)} ${esc(b.last_name)}`,
    String(b.days_allocated ?? 0),
    String(b.days_taken ?? 0),
    String(b.days_pending ?? 0),
    String(b.days_remaining ?? 0),
  ])
  const totalAllocated = (data.balances || []).reduce((s: number, b: any) => s + Number(b.days_allocated || 0), 0)
  const totalTaken = (data.balances || []).reduce((s: number, b: any) => s + Number(b.days_taken || 0), 0)
  const totalPending = (data.balances || []).reduce((s: number, b: any) => s + Number(b.days_pending || 0), 0)
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${buildReportStyles()}</style></head><body>
    ${coverPage('Leave Overview', orgName, 'Staff leave balances, usage, and pending requests')}
    <h1>Leave Summary</h1>
    <div class="summary-grid">
      <div class="summary-card"><div class="num">${totalAllocated.toFixed(0)}</div><div class="label">Total Days Allocated</div></div>
      <div class="summary-card"><div class="num">${totalTaken.toFixed(0)}</div><div class="label">Days Taken</div></div>
      <div class="summary-card"><div class="num">${totalPending.toFixed(0)}</div><div class="label">Pending Approval</div></div>
    </div>
    <h2>Leave Balances (${rows.length})</h2>
    ${rows.length ? table(['Staff Name', 'Allocated Days', 'Used', 'Pending', 'Remaining'], rows) : '<p>No leave balances configured.</p>'}
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #D1D5DB;font-size:10px;color:#9CA3AF;text-align:center">CareDesk Report &bull; Generated ${now()}</div>
  </body></html>`
}

export function leaveOverviewCsv(data: any): string {
  const headers = ['Staff Name', 'Allocated Days', 'Used', 'Pending', 'Remaining']
  const rows = (data.balances || []).map((b: any) => [
    `${b.first_name} ${b.last_name}`,
    String(b.days_allocated ?? 0),
    String(b.days_taken ?? 0),
    String(b.days_pending ?? 0),
    String(b.days_remaining ?? 0),
  ])
  return toCsv(headers, rows)
}

// --- Service User Roster ---
export function buildServiceUserRosterHtml(data: any, orgName = 'CareDesk'): string {
  const rows = (data.service_users || []).map((su: any) => [
    `${esc(su.first_name)} ${esc(su.last_name)}`,
    esc(su.location_name || '-'),
    statusBadge(su.status || 'active'),
    su.created_at ? new Date(su.created_at).toLocaleDateString() : '-',
    `${esc(su.key_worker_first || '')} ${esc(su.key_worker_last || '')}`.trim() || '-',
    esc(su.care_level || '-'),
  ])
  const active = (data.service_users || []).filter((s: any) => s.status === 'active').length
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${buildReportStyles()}</style></head><body>
    ${coverPage('Service User Roster', orgName, 'Active service users by location with status overview')}
    <h1>Service User Summary</h1>
    <div class="summary-grid">
      <div class="summary-card"><div class="num">${data.service_users?.length || 0}</div><div class="label">Total</div></div>
      <div class="summary-card"><div class="num">${active}</div><div class="label">Active</div></div>
    </div>
    <h2>Service Users (${rows.length})</h2>
    ${rows.length ? table(['Name', 'Location', 'Status', 'Start Date', 'Key Worker', 'Care Level'], rows) : '<p>No service users.</p>'}
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #D1D5DB;font-size:10px;color:#9CA3AF;text-align:center">CareDesk Report &bull; Generated ${now()}</div>
  </body></html>`
}

export function serviceUserRosterCsv(data: any): string {
  const headers = ['Name', 'Location', 'Status', 'Start Date', 'Key Worker', 'Care Level']
  const rows = (data.service_users || []).map((su: any) => [
    `${su.first_name} ${su.last_name}`,
    su.location_name || '',
    su.status || '',
    su.created_at ? new Date(su.created_at).toLocaleDateString() : '',
    `${su.key_worker_first || ''} ${su.key_worker_last || ''}`.trim(),
    su.care_level || '',
  ])
  return toCsv(headers, rows)
}

// --- Medication Administration ---
export function buildMedicationAdminHtml(data: any, orgName = 'CareDesk'): string {
  const rows = (data.medications || []).map((m: any) => [
    esc(m.medication_name),
    esc(m.scheduled_times || '-'),
    `${m.administered_pct ?? 0}%`,
    String(m.missed_count ?? 0),
    String(m.refused_count ?? 0),
    String(m.self_administered_count ?? 0),
  ])
  const avgPct = (data.medications || []).length
    ? ((data.medications || []).reduce((s: number, m: any) => s + Number(m.administered_pct || 0), 0) / data.medications.length).toFixed(1)
    : '0'
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${buildReportStyles()}</style></head><body>
    ${coverPage('Medication Administration', orgName, 'MAR compliance rates and medication administration records')}
    <h1>Administration Summary</h1>
    <div class="summary-grid">
      <div class="summary-card"><div class="num">${data.medications?.length || 0}</div><div class="label">Medications</div></div>
      <div class="summary-card"><div class="num">${avgPct}%</div><div class="label">Average Compliance</div></div>
      <div class="summary-card"><div class="num">${(data.medications || []).reduce((s: number, m: any) => s + (m.missed_count || 0), 0)}</div><div class="label">Total Missed</div></div>
    </div>
    <h2>Medication Details (${rows.length})</h2>
    ${rows.length ? table(['Medication', 'Scheduled Times', 'Administered %', 'Missed', 'Refused', 'Self-Administered'], rows) : '<p>No medication records.</p>'}
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #D1D5DB;font-size:10px;color:#9CA3AF;text-align:center">CareDesk Report &bull; Generated ${now()}</div>
  </body></html>`
}

export function medicationAdminCsv(data: any): string {
  const headers = ['Medication', 'Scheduled Times', 'Administered %', 'Missed', 'Refused', 'Self-Administered']
  const rows = (data.medications || []).map((m: any) => [
    m.medication_name,
    m.scheduled_times || '',
    String(m.administered_pct ?? 0),
    String(m.missed_count ?? 0),
    String(m.refused_count ?? 0),
    String(m.self_administered_count ?? 0),
  ])
  return toCsv(headers, rows)
}

type HtmlBuilder = (data: any, orgName?: string) => string
type CsvBuilder = (data: any) => string

export const reportBuilders: Record<string, { html: HtmlBuilder; csv: CsvBuilder }> = {
  'staff-compliance': { html: buildStaffComplianceHtml, csv: staffComplianceCsv },
  'training-matrix': { html: buildTrainingMatrixHtml, csv: trainingMatrixCsv },
  'incident-log': { html: buildIncidentLogHtml, csv: incidentLogCsv },
  'leave-overview': { html: buildLeaveOverviewHtml, csv: leaveOverviewCsv },
  'service-user-roster': { html: buildServiceUserRosterHtml, csv: serviceUserRosterCsv },
  'medication-admin': { html: buildMedicationAdminHtml, csv: medicationAdminCsv },
}
