import { useMemo, useState } from 'react'
import {
  Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions,
  DialogContent, DialogTitle, Grid, IconButton, MenuItem, Paper, Stack, Tab, Table,
  TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, TextField, Typography,
} from '@mui/material'
import { Add as AddIcon, Delete as DeleteIcon, Edit as EditIcon, History as HistoryIcon, Receipt as ReceiptIcon, Wallet as WalletIcon } from '@mui/icons-material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import api from '../../services/api'

const NAVY = '#0F4C81'
const CATEGORIES = [{ value: 'food', label: 'Food' }, { value: 'clothing', label: 'Clothing' }, { value: 'activities', label: 'Activities' }, { value: 'transport', label: 'Transport' }, { value: 'personal', label: 'Personal' }, { value: 'health', label: 'Health' }, { value: 'other', label: 'Other' }]
const SOURCE_LABELS: Record<string, string> = { house: 'House funds', person: 'Person funds' }
function asArray(value: any, keys: string[] = []) { if (Array.isArray(value)) return value; for (const key of keys) if (Array.isArray(value?.[key])) return value[key]; return Array.isArray(value?.data) ? value.data : [] }
function today() { return new Date().toISOString().slice(0, 10) }

export default function ExpensesPage() {
  const qc = useQueryClient()
  const [tab, setTab] = useState(0); const [createOpen, setCreateOpen] = useState(false); const [editId, setEditId] = useState<string | null>(null)
  const [filterSource, setFilterSource] = useState(''); const [filterCategory, setFilterCategory] = useState(''); const [filterPerson, setFilterPerson] = useState('')
  const [topUpOpen, setTopUpOpen] = useState(false); const [reconcileOpen, setReconcileOpen] = useState(false)
  const { data: expenseData, isLoading } = useQuery({ queryKey: ['expenses', filterSource, filterCategory, filterPerson], queryFn: () => api.get('/expenses', { params: { moneySource: filterSource || undefined, category: filterCategory || undefined, personId: filterPerson || undefined } }).then(r => r.data) })
  const expenses = asArray(expenseData, ['expenses'])
  const { data: stats } = useQuery({ queryKey: ['expense-stats'], queryFn: () => api.get('/expenses/stats').then(r => r.data) })
  const { data: peopleData } = useQuery({ queryKey: ['people-expenses'], queryFn: () => api.get('/people?limit=200').then(r => r.data) })
  const people = asArray(peopleData, ['people'])
  const { data: balancesData } = useQuery({ queryKey: ['petty-cash-balances'], queryFn: () => api.get('/expenses/petty-cash/balances').then(r => r.data) })
  const balances = asArray(balancesData, ['balances'])
  const { data: transactionData } = useQuery({ queryKey: ['petty-cash-transactions'], queryFn: () => api.get('/expenses/petty-cash/transactions').then(r => r.data) })
  const transactions = asArray(transactionData, ['transactions'])
  const { data: locationsData } = useQuery({ queryKey: ['locations'], queryFn: () => api.get('/settings/locations').then(r => r.data) })
  const locations = asArray(locationsData, ['locations'])
  const createMutation = useMutation({ mutationFn: (data: any) => api.post('/expenses', data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['expenses'] }); qc.invalidateQueries({ queryKey: ['expense-stats'] }); setCreateOpen(false) } })
  const updateMutation = useMutation({ mutationFn: ({ id, data }: any) => api.patch(`/expenses/${id}`, data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['expenses'] }); qc.invalidateQueries({ queryKey: ['expense-stats'] }); setEditId(null) } })
  const deleteMutation = useMutation({ mutationFn: (id: string) => api.delete(`/expenses/${id}`), onSuccess: () => { qc.invalidateQueries({ queryKey: ['expenses'] }); qc.invalidateQueries({ queryKey: ['expense-stats'] }) } })
  const totalHouse = useMemo(() => expenses.filter((e: any) => e.money_source === 'house').reduce((sum: number, e: any) => sum + Number(e.amount_pence || 0), 0), [expenses])
  const totalPerson = useMemo(() => expenses.filter((e: any) => e.money_source !== 'house').reduce((sum: number, e: any) => sum + Number(e.amount_pence || 0), 0), [expenses])

  if (isLoading) return <Box sx={{ textAlign: 'center', py: 8 }}><CircularProgress sx={{ color: NAVY }} /></Box>
  return <Box>
    <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ xs: 'stretch', sm: 'center' }} spacing={2} mb={3}><Box><Typography variant="h5" fontWeight={800}>Expenses</Typography><Typography variant="body2" color="text.secondary">Keep house spending and people&apos;s money separate, traceable, and easy to reconcile.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<WalletIcon />} onClick={() => setTopUpOpen(true)} sx={{ textTransform: 'none' }}>Top up</Button><Button variant="contained" startIcon={<AddIcon />} onClick={() => setCreateOpen(true)} sx={{ bgcolor: NAVY, textTransform: 'none' }}>Add expense</Button></Stack></Stack>
    <Grid container spacing={2} mb={3}>{[['Total ledger', stats?.total_amount_pounds || 0, ''], ['House funds', totalHouse / 100, 'house'], ['Person funds', totalPerson / 100, 'person'], ['Entries', stats?.total_expenses || 0, 'count']].map(([label, value, key]) => <Grid item xs={12} sm={6} md={3} key={String(label)}><Card sx={{ border: '1px solid #E5E7EB', boxShadow: 'none' }}><CardContent><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" fontWeight={800}>{key === 'count' ? value : `£${Number(value).toFixed(2)}`}</Typography></CardContent></Card></Grid>)}</Grid>
    <Tabs value={tab} onChange={(_, v) => setTab(v)} sx={{ borderBottom: '1px solid #E5E7EB' }}><Tab icon={<ReceiptIcon />} iconPosition="start" label="Spending ledger" sx={{ textTransform: 'none' }} /><Tab icon={<WalletIcon />} iconPosition="start" label="Petty cash" sx={{ textTransform: 'none' }} /></Tabs>
    {tab === 0 && <Box sx={{ pt: 2 }}><Paper sx={{ p: 1.5, mb: 2, border: '1px solid #E5E7EB' }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5}><TextField select size="small" label="Money source" value={filterSource} onChange={e => setFilterSource(e.target.value)} sx={{ minWidth: 170 }}><MenuItem value="">All sources</MenuItem><MenuItem value="house">House funds</MenuItem><MenuItem value="person">Person funds</MenuItem></TextField><TextField select size="small" label="Person" value={filterPerson} onChange={e => setFilterPerson(e.target.value)} sx={{ minWidth: 200 }}><MenuItem value="">All people</MenuItem>{people.map((p: any) => <MenuItem key={p.id} value={p.id}>{p.first_name} {p.last_name}</MenuItem>)}</TextField><TextField select size="small" label="Category" value={filterCategory} onChange={e => setFilterCategory(e.target.value)} sx={{ minWidth: 150 }}><MenuItem value="">All categories</MenuItem>{CATEGORIES.map(c => <MenuItem key={c.value} value={c.value}>{c.label}</MenuItem>)}</TextField></Stack></Paper><TableContainer component={Paper} sx={{ border: '1px solid #E5E7EB' }}><Table size="small"><TableHead><TableRow>{['Date', 'Money source', 'Person', 'Category', 'Description', 'Amount', 'Added by', ''].map(h => <TableCell key={h} sx={{ fontWeight: 800, color: 'text.secondary' }}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{expenses.length === 0 ? <TableRow><TableCell colSpan={8} align="center" sx={{ py: 6, color: '#9CA3AF' }}>No expenses recorded.</TableCell></TableRow> : expenses.map((e: any) => <TableRow key={e.id} hover><TableCell>{new Date(e.incurred_date).toLocaleDateString('en-GB')}</TableCell><TableCell><Chip size="small" label={SOURCE_LABELS[e.money_source] || 'Person funds'} color={e.money_source === 'house' ? 'info' : 'default'} /></TableCell><TableCell>{e.money_source === 'house' ? '—' : e.person_name || '—'}</TableCell><TableCell><Chip label={e.category} size="small" /></TableCell><TableCell>{e.description || '—'}</TableCell><TableCell>£{(Number(e.amount_pence || 0) / 100).toFixed(2)}</TableCell><TableCell>{e.created_by_name || '—'}</TableCell><TableCell><IconButton size="small" onClick={() => setEditId(e.id)}><EditIcon fontSize="small" /></IconButton><IconButton size="small" color="error" onClick={() => deleteMutation.mutate(e.id)}><DeleteIcon fontSize="small" /></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>}
    {tab === 1 && <Box sx={{ pt: 2 }}><Stack direction="row" spacing={1} mb={2}><Button variant="outlined" startIcon={<WalletIcon />} onClick={() => setTopUpOpen(true)}>Top up</Button><Button variant="outlined" startIcon={<HistoryIcon />} onClick={() => setReconcileOpen(true)}>Reconcile</Button></Stack><Grid container spacing={2} mb={3}>{balances.map((b: any) => <Grid item xs={12} sm={6} md={4} key={b.id}><Card sx={{ border: '1px solid #E5E7EB', boxShadow: 'none' }}><CardContent><Typography variant="subtitle2">{b.location_name}</Typography><Typography variant="h4" color="primary">£{(Number(b.current_balance_pence || 0) / 100).toFixed(2)}</Typography><Typography variant="caption" color="text.secondary">{b.last_reconciled_at ? `Last reconciled: ${new Date(b.last_reconciled_at).toLocaleDateString('en-GB')}` : 'Never reconciled'}</Typography></CardContent></Card></Grid>)}</Grid><TableContainer component={Paper} sx={{ border: '1px solid #E5E7EB' }}><Table size="small"><TableHead><TableRow><TableCell>Date</TableCell><TableCell>Location</TableCell><TableCell>Type</TableCell><TableCell align="right">Amount</TableCell><TableCell>Balance</TableCell><TableCell>Notes</TableCell></TableRow></TableHead><TableBody>{transactions.map((t: any) => <TableRow key={t.id}><TableCell>{new Date(t.created_at).toLocaleString('en-GB')}</TableCell><TableCell>{t.location_name}</TableCell><TableCell><Chip label={t.type.replace('_', ' ')} size="small" /></TableCell><TableCell align="right">£{(Number(t.amount_pence || 0) / 100).toFixed(2)}</TableCell><TableCell>£{(Number(t.new_balance_pence || 0) / 100).toFixed(2)}</TableCell><TableCell>{t.notes || '—'}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>}
    <Dialog open={createOpen || !!editId} onClose={() => { setCreateOpen(false); setEditId(null) }} maxWidth="sm" fullWidth><DialogTitle>{editId ? 'Edit expense' : 'Add expense'}</DialogTitle><ExpenseForm people={people} initialData={editId ? expenses.find((e: any) => e.id === editId) : undefined} onSubmit={data => editId ? updateMutation.mutate({ id: editId, data }) : createMutation.mutate(data)} onCancel={() => { setCreateOpen(false); setEditId(null) }} isLoading={createMutation.isPending || updateMutation.isPending} /></Dialog>
    <PettyCashDialog open={topUpOpen} title="Top up petty cash" locations={locations} onClose={() => setTopUpOpen(false)} onSubmit={(data: any) => api.post('/expenses/petty-cash/top-up', data).then(() => { qc.invalidateQueries({ queryKey: ['petty-cash-balances'] }); qc.invalidateQueries({ queryKey: ['petty-cash-transactions'] }); setTopUpOpen(false) })} kind="top_up" />
    <PettyCashDialog open={reconcileOpen} title="Reconcile petty cash" locations={locations} onClose={() => setReconcileOpen(false)} onSubmit={(data: any) => api.post('/expenses/petty-cash/reconcile', data).then(() => { qc.invalidateQueries({ queryKey: ['petty-cash-balances'] }); qc.invalidateQueries({ queryKey: ['petty-cash-transactions'] }); setReconcileOpen(false) })} kind="reconcile" />
  </Box>
}

function ExpenseForm({ people, initialData, onSubmit, onCancel, isLoading }: { people: any[]; initialData?: any; onSubmit: (data: any) => void; onCancel: () => void; isLoading: boolean }) {
  const [source, setSource] = useState(initialData?.money_source || 'person'); const [personId, setPersonId] = useState(initialData?.person_id || ''); const [category, setCategory] = useState(initialData?.category || 'food'); const [amount, setAmount] = useState(initialData ? Number(initialData.amount_pence) / 100 : 0); const [description, setDescription] = useState(initialData?.description || ''); const [paymentMethod, setPaymentMethod] = useState(initialData?.payment_method || 'cash'); const [date, setDate] = useState(initialData?.incurred_date || today())
  return <><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField select label="Money source" fullWidth value={source} onChange={e => setSource(e.target.value)}><MenuItem value="person">Person funds</MenuItem><MenuItem value="house">House funds</MenuItem></TextField>{source === 'person' && <TextField select label="Person" fullWidth required value={personId} onChange={e => setPersonId(e.target.value)}><MenuItem value="">Select person</MenuItem>{people.map(p => <MenuItem key={p.id} value={p.id}>{p.first_name} {p.last_name}</MenuItem>)}</TextField>}<TextField select label="Category" fullWidth value={category} onChange={e => setCategory(e.target.value)}>{CATEGORIES.map(c => <MenuItem key={c.value} value={c.value}>{c.label}</MenuItem>)}</TextField><TextField select label="Payment method" fullWidth value={paymentMethod} onChange={e => setPaymentMethod(e.target.value)}><MenuItem value="cash">Cash</MenuItem><MenuItem value="card">Card</MenuItem><MenuItem value="bank_transfer">Bank transfer</MenuItem><MenuItem value="direct_debit">Direct debit</MenuItem></TextField><TextField label="Amount (£)" type="number" fullWidth value={amount} onChange={e => setAmount(parseFloat(e.target.value) || 0)} inputProps={{ min: 0.01, step: 0.01 }} /><TextField label="Description / reason" fullWidth multiline rows={3} value={description} onChange={e => setDescription(e.target.value)} /><TextField label="Date" type="date" fullWidth InputLabelProps={{ shrink: true }} value={date} onChange={e => setDate(e.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={onCancel}>Cancel</Button><Button variant="contained" onClick={() => onSubmit({ personId: source === 'person' ? personId : null, moneySource: source, paymentMethod, category, amountPence: Math.round(amount * 100), description, incurredDate: date })} disabled={!amount || !date || (source === 'person' && !personId) || isLoading}>{isLoading ? <CircularProgress size={20} /> : initialData ? 'Update expense' : 'Add expense'}</Button></DialogActions></>
}

function PettyCashDialog({ open, title, locations, onClose, onSubmit, kind }: any) { const [locationId, setLocationId] = useState(''); const [amount, setAmount] = useState(0); const [notes, setNotes] = useState(''); return <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth><DialogTitle>{title}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField select label="Location" fullWidth value={locationId} onChange={e => setLocationId(e.target.value)}>{locations.map((l: any) => <MenuItem key={l.id} value={l.id}>{l.name}</MenuItem>)}</TextField><TextField label={kind === 'top_up' ? 'Amount (£)' : 'Actual balance (£)'} type="number" fullWidth value={amount} onChange={e => setAmount(parseFloat(e.target.value) || 0)} inputProps={{ min: 0, step: 0.01 }} /><TextField label="Notes" multiline rows={2} fullWidth value={notes} onChange={e => setNotes(e.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!locationId || (kind === 'top_up' ? amount <= 0 : amount < 0)} onClick={() => onSubmit(kind === 'top_up' ? { locationId, amountPence: Math.round(amount * 100), notes } : { locationId, actualBalancePence: Math.round(amount * 100), notes })}>{kind === 'top_up' ? 'Top up' : 'Reconcile'}</Button></DialogActions></Dialog> }
