import { ArrowBack, ArrowForward, CalendarMonth, Share } from '@mui/icons-material'
import { Box, Button, Chip, Container, Divider, Grid, Stack, Typography } from '@mui/material'
import { Link, useNavigate, useParams } from 'react-router-dom'
import MarketingLayout from '../../components/marketing/MarketingLayout'
import PageMeta from '../../components/PageMeta'

const C = { navy: '#0F4C81', emerald: '#10B981', emeraldDeep: '#047857', ink: '#1B2430', dark: '#141C24', bone: '#F7F4EE', mist: '#5B6672', line: '#E7E1D6', white: '#FFFFFF' }

type Article = { slug: string; title: string; category: string; date: string; readingTime: string; excerpt: string; body: Array<{ heading: string; paragraphs: string[] }> }

const articles: Article[] = [
  { slug: 'inspection-ready-care-records', title: 'What inspection-ready care records look like in practice', category: 'Compliance', date: '2026-09-01', readingTime: '6 min read', excerpt: 'Inspection readiness is easier to maintain when evidence is created as part of ordinary care work.', body: [
    { heading: 'Readiness is a working habit', paragraphs: ['Inspection preparation should not depend on rebuilding a service history from scattered documents. A stronger approach is to make everyday records clear, current and easy to trace.', 'That means connecting the person’s plan, the care delivered, the review, the action and the evidence behind it.'] },
    { heading: 'What to make visible', paragraphs: ['Teams should be able to find who recorded an event, when it happened, what was observed and what happened next. Managers also need a practical way to see overdue reviews, open actions and gaps in workforce evidence.', 'Digital tools can support this process, but they do not replace local policies, professional judgement or the requirements of the relevant regulator.'] },
    { heading: 'A useful test', paragraphs: ['Choose one recent care event and follow it through the system: from the plan, to the note, to any risk or incident record, to review and follow-up. If the chain is easy to follow, your operation is building evidence continuously.'] },
  ] },
  { slug: 'domiciliary-care-scheduling', title: 'A practical approach to domiciliary care scheduling', category: 'Domiciliary care', date: '2026-08-20', readingTime: '5 min read', excerpt: 'Good scheduling balances client needs, carer availability, travel and the realities of the working day.', body: [
    { heading: 'Start with the visit, not the spreadsheet', paragraphs: ['A domiciliary schedule is more than a list of names and times. Each call has a client, a care requirement, a time window, a location and a person who needs a workable route.', 'The best planning view keeps those pieces together and makes exceptions visible before they become missed or late visits.'] },
    { heading: 'Make exceptions actionable', paragraphs: ['A missed or delayed call should not disappear into a status column. Managers need a clear follow-up path: record what happened, contact the right people, escalate where required and keep the resolution history with the visit.', 'Availability and leave should be considered before assignment, while changes remain subject to manager review.'] },
    { heading: 'Keep the field experience short', paragraphs: ['Carers need a focused mobile flow for the work in front of them: see the route, check in and out, record factual notes and report a disruption. The office view can carry the wider planning and governance context.'] },
  ] },
  { slug: 'responsible-ai-in-care', title: 'Using AI responsibly in care operations', category: 'AI & care', date: '2026-08-08', readingTime: '7 min read', excerpt: 'AI can reduce administration and surface patterns, but care teams must remain responsible for interpretation and action.', body: [
    { heading: 'Assist, do not invent', paragraphs: ['An AI-assisted care workflow should preserve the original record, make the assistance visible and avoid adding facts that were not present in the source information.', 'A suggested summary is not a clinical conclusion. A possible signal is not a diagnosis. Those distinctions matter because care information is sensitive and decisions affect real people.'] },
    { heading: 'Trace every useful statement', paragraphs: ['Managers should be able to see which source records support an AI-generated statement, when those records were created and what uncertainty remains. This makes review practical rather than ceremonial.'] },
    { heading: 'Permissions come first', paragraphs: ['An AI assistant must work within the same organisation and role boundaries as the rest of the application. It must not receive records that the requesting user could not already access, and each meaningful action should be auditable.'] },
  ] },
]

export default function PublicBlogPage() {
  const { slug } = useParams<{ slug?: string }>()
  const article = slug ? articles.find((item) => item.slug === slug) : undefined
  return article ? <ArticlePage article={article} /> : <BlogIndex />
}

function BlogIndex() {
  const navigate = useNavigate()
  return <MarketingLayout><PageMeta title="Care technology blog" description="Practical guidance on care operations, compliance, domiciliary care, supported living and responsible AI." canonicalPath="/blog" /><Box sx={{ bgcolor: C.bone, py: { xs: 8, md: 12 }, borderBottom: `1px solid ${C.line}` }}><Container maxWidth="lg"><Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}><Box sx={{ width: 9, height: 9, bgcolor: C.emerald, borderRadius: 1 }} /><Typography sx={{ color: C.navy, fontSize: '.72rem', fontWeight: 800, letterSpacing: '.12em', textTransform: 'uppercase' }}>Care technology · guidance · product thinking</Typography></Stack><Typography variant="h1" sx={{ fontSize: { xs: '2.6rem', md: '4rem' }, fontWeight: 900, lineHeight: 1.03, maxWidth: 820, mb: 2 }}>Practical ideas for running better care operations.</Typography><Typography sx={{ color: C.mist, fontSize: '1.12rem', maxWidth: 700, lineHeight: 1.75 }}>Clear, evidence-led reading for domiciliary and supported living providers. No invented credentials, endorsements or customer claims.</Typography></Container></Box><Box sx={{ py: { xs: 8, md: 12 } }}><Container maxWidth="lg"><Grid container spacing={3}>{articles.map((article) => <Grid item xs={12} md={4} key={article.slug}><Box component={Link} to={`/blog/${article.slug}`} sx={{ display: 'flex', flexDirection: 'column', height: '100%', p: 3, border: `1px solid ${C.line}`, textDecoration: 'none', color: 'inherit', '&:hover': { borderColor: C.navy } }}><Chip label={article.category} size="small" sx={{ alignSelf: 'flex-start', mb: 2, bgcolor: '#EEF5FA', color: C.navy, fontWeight: 800 }} /><Typography variant="h2" sx={{ fontSize: '1.35rem', fontWeight: 900, lineHeight: 1.2, mb: 1.5 }}>{article.title}</Typography><Typography sx={{ color: C.mist, lineHeight: 1.65, flex: 1 }}>{article.excerpt}</Typography><Stack direction="row" spacing={2} sx={{ mt: 3, color: C.mist }}><Typography sx={{ fontSize: '.78rem' }}>{article.date}</Typography><Typography sx={{ fontSize: '.78rem' }}>{article.readingTime}</Typography></Stack><Button endIcon={<ArrowForward />} onClick={(event) => { event.preventDefault(); navigate(`/blog/${article.slug}`) }} sx={{ alignSelf: 'flex-start', px: 0, mt: 1.5, color: C.navy, fontWeight: 800 }}>Read article</Button></Box></Grid>)}</Grid></Container></Box></MarketingLayout>
}

function ArticlePage({ article }: { article: Article }) {
  const navigate = useNavigate()
  const share = async () => { const url = window.location.href; if (navigator.share) await navigator.share({ title: article.title, url }); else await navigator.clipboard?.writeText(url) }
  return <MarketingLayout><PageMeta title={article.title} description={article.excerpt} canonicalPath={`/blog/${article.slug}`} ogType="article" structuredData={{ '@context': 'https://schema.org', '@type': 'Article', headline: article.title, datePublished: article.date, author: { '@type': 'Organization', name: 'MeticleCare' }, description: article.excerpt }} /><Box sx={{ bgcolor: C.bone, py: { xs: 7, md: 10 }, borderBottom: `1px solid ${C.line}` }}><Container maxWidth="md"><Button startIcon={<ArrowBack />} onClick={() => navigate('/blog')} sx={{ px: 0, color: C.navy, fontWeight: 800, mb: 4 }}>All articles</Button><Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}><Chip label={article.category} size="small" sx={{ bgcolor: C.emerald, color: C.white, fontWeight: 800 }} /><Typography sx={{ color: C.mist, fontSize: '.82rem' }}>{article.readingTime}</Typography></Stack><Typography variant="h1" sx={{ fontSize: { xs: '2.45rem', md: '3.8rem' }, fontWeight: 900, lineHeight: 1.04, mb: 2 }}>{article.title}</Typography><Typography sx={{ color: C.mist, fontSize: '1.1rem', lineHeight: 1.75 }}>{article.excerpt}</Typography><Stack direction="row" spacing={2} alignItems="center" sx={{ mt: 3 }}><Stack direction="row" spacing={.75} alignItems="center"><CalendarMonth sx={{ color: C.mist, fontSize: 17 }} /><Typography sx={{ color: C.mist, fontSize: '.82rem' }}>{article.date}</Typography></Stack><Button startIcon={<Share />} onClick={share} sx={{ color: C.navy, fontWeight: 800 }}>Share</Button></Stack></Container></Box><Box component="article" sx={{ py: { xs: 7, md: 10 } }}><Container maxWidth="md">{article.body.map((section) => <Box key={section.heading} sx={{ mb: 6 }}><Typography variant="h2" sx={{ fontSize: { xs: '1.7rem', md: '2.2rem' }, fontWeight: 900, mb: 2 }}>{section.heading}</Typography>{section.paragraphs.map((paragraph) => <Typography key={paragraph} component="p" sx={{ color: C.mist, fontSize: '1.05rem', lineHeight: 1.85, mb: 2 }}>{paragraph}</Typography>)}</Box>)}<Divider sx={{ borderColor: C.line, my: 5 }} /><Typography sx={{ color: C.mist, fontSize: '.86rem', lineHeight: 1.7 }}>MeticleCare provides software and general information. It is not legal, regulatory or clinical advice. Providers remain responsible for their own policies, procedures, professional judgement and regulatory obligations.</Typography></Container></Box></MarketingLayout>
}
