-- Provenance for AI-generated meal plans.
--
-- T1-11: AI output labelling. Daily notes already carry generated_by_ai, and
-- incident triage is stored in its own ai_triage column — but a meal plan
-- generated by the AI and saved as a template became indistinguishable from one
-- a dietitian wrote by hand. That matters more here than the missing label on
-- the results panel: the panel disappears when the dialog closes, the template
-- stays. Whoever reads the plan a month later — including an inspector asking
-- who wrote the allergen and texture decisions — deserves to know.
--
-- Nullable, not default false: existing rows were written by humans and we
-- cannot prove which, so NULL means "no AI involvement recorded", which is
-- honest, while FALSE would assert a human authorship we did not check.
--
-- The column is read-side too: the list and detail endpoints return it, the
-- saved-plan dialog shows it, and PrintableWeeklyMealPlan already carries the
-- "AI-generated" line for print runs.
ALTER TABLE meal_plan_templates
  ADD COLUMN IF NOT EXISTS generated_by_ai BOOLEAN;

-- Guarded for idempotency in the same style as migrations 128–130.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'meal_plan_templates' AND column_name = 'generated_by_ai'
  ) THEN
    -- Nothing to do: the ADD COLUMN above already ran on a fresh database.
    NULL;
  END IF;
END $$;
